name: Build Executables

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: build-env
        python-version: '3.9'

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install -c conda-forge pyinstaller
        pip install -r requirements.txt

    - name: Build executable
      shell: bash -l {0}
      run: pyinstaller --onefile calculator.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: calculator-${{ matrix.os }}
        path: dist/*
